--liquibase formatted sql

--changeset d.lebedev:001-create-link-table

CREATE TABLE links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base62_code BIGINT NOT NULL UNIQUE,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

--rollback DROP TABLE links;
